### ISSUE TITLE
Add favicon to site - Open Pull Request

### ISSUE THREAD

**Issue by shaunagm** [psf/python-in-edu#14]
Favicons are set in the head of the html file, which right now is in the template file `full_width_base.html`. I believe there's an existing favicon that's just the Python logo, in one of the other PSF repositories or on the website. So to do this task, please track down the icon (or make a cool new one), add it to the static_sources, and stick a reference to it via Django's template tags in `full_width_base.html`.

**Comment by martin-martin** [comment]
I'd like to tackle this during the upcoming PyCon sprint :)

**Comment by martin-martin** [comment]
Could be fun to customize it a little, maybe add some glasses to one of the snakes, and some hair to the other one (similar to how the graphics are on the site) :)

LMK if this is wanted and I could give it a go, too 🎨 🤓

**Comment by meg-ray** [comment]
> Could be fun to customize it a little, maybe add some glasses to one of the snakes, and some hair to the other one (similar to how the graphics are on the site) :)
> 
> LMK if this is wanted and I could give it a go, too

@martin-martin What a fun idea! If you haven't already, please feel free to go for it!

**Comment by martin-martin** [comment]
@meg-ray added a design that takes glasses and hair from [pythonineducation](http://pythonineducation.org/en/). 🐍

**Comment by anaypant** [comment]
Hi Meg,
I just fixed this as my first issue on my fork @ https://github.com/anaypant/python-in-edu. Please allow me to make a pull request, so I can merge the new favicon. Let me know which favicon you want me to use. I am using 

https://github.com/anaypant/python-in-edu/blob/master/python-in-edu/static_source/images/favicon.ico

right now. Thanks!
-Anay
