### ISSUE TITLE
Fix resource list view - Open Pull Request

### ISSUE THREAD

**Issue by shaunagm** [psf/python-in-edu#18]
I was checking in on the site to see how it was doing, and noticed that the resource list is displaying weirdly (the full features of the data table are lost). I did a bit of digging, and I think it may be due to [this update](https://github.com/psf/python-in-edu/pull/17/files) where `resource.use_type` was added as a data-child in the header but not in the data for each row  (see [this function](https://github.com/psf/python-in-edu/blob/master/python-in-edu/resources/templates/resources/resource_list.html#L87) called [here](https://github.com/psf/python-in-edu/blob/master/python-in-edu/resources/templates/resources/resource_list.html#L176)).  Here's the [relevant docs](https://datatables.net/reference/api/row().child()).

**Comment by sijanonly** [comment]
@shaunagm 
I am working on it.
