### ISSUE TITLE
research libraries for forums in flask

### ISSUE THREAD

**Issue by meg-ray** [psf/python-in-edu#4]
We will need to select and integrate a library to create forum functionality. If you have experience with this, let's chat on the contributor's channel: https://join.slack.com/t/pythoneducators/shared_invite/zt-80fa68ea-jT4dTxgdGBshz9jft13S~g

**Comment by YashVadhadiya** [comment]
> _No description provided._

How can i help you?

**Comment by meg-ray** [comment]
Hi Yash, if there is a ticket that interests you, let us know! You can join the contributor community for this project on Slack: https://join.slack.com/t/pythoneducators/shared_invite/zt-80fa68ea-jT4dTxgdGBshz9jft13S~g

**Comment by mwt** [comment]
I don't have experience with this, but the official PSF forums are done in MyBB (PHP). I know there was talk of moving these over to Python, but this didn't happen. It might be helpful to understand what got in their way.

I found this library: [FlaskBB](https://github.com/flaskbb/flaskbb)

**Comment by meg-ray** [comment]
I agree that FlaskBB seems like the best option for a Python-based forum, Misago also looks good. I really like some of the more modern software like Discourse, Tribe, or Flarum. I wish there were an open source option in Python!
